`timescale 1 ns/100 ps
// Version: v11.0 11.0.0.23


module IR_QUEUE(
       DATA,
       Q,
       WE,
       RE,
       WCLOCK,
       RCLOCK,
       FULL,
       EMPTY,
       RESET,
       DVLD
    );
input  [7:0] DATA;
output [7:0] Q;
input  WE;
input  RE;
input  WCLOCK;
input  RCLOCK;
output FULL;
output EMPTY;
input  RESET;
output DVLD;

    wire READ_RESET_P, WRITE_RESET_P, \MEM_RADDR[0] , 
        \RBINNXTSHIFT[0] , \WBINSYNCSHIFT[0] , \MEM_WADDR[0] , 
        \WBINNXTSHIFT[0] , \RBINSYNCSHIFT[0] , \MEM_RADDR[1] , 
        \RBINNXTSHIFT[1] , \WBINSYNCSHIFT[1] , \MEM_WADDR[1] , 
        \WBINNXTSHIFT[1] , \RBINSYNCSHIFT[1] , \MEM_RADDR[2] , 
        \RBINNXTSHIFT[2] , \WBINSYNCSHIFT[2] , \MEM_WADDR[2] , 
        \WBINNXTSHIFT[2] , \RBINSYNCSHIFT[2] , \MEM_RADDR[3] , 
        \RBINNXTSHIFT[3] , \WBINSYNCSHIFT[3] , \MEM_WADDR[3] , 
        \WBINNXTSHIFT[3] , \RBINSYNCSHIFT[3] , \MEM_RADDR[4] , 
        \RBINNXTSHIFT[4] , \WBINSYNCSHIFT[4] , \MEM_WADDR[4] , 
        \WBINNXTSHIFT[4] , \RBINSYNCSHIFT[4] , \MEM_RADDR[5] , 
        \RBINNXTSHIFT[5] , \WBINSYNCSHIFT[5] , \MEM_WADDR[5] , 
        \WBINNXTSHIFT[5] , \RBINSYNCSHIFT[5] , \MEM_RADDR[6] , 
        \RBINNXTSHIFT[6] , READDOMAIN_WMSB, \MEM_WADDR[6] , 
        \WBINNXTSHIFT[6] , \RBINSYNCSHIFT[6] , FULLINT, MEMORYWE, 
        MEMWENEG, \WGRY[0] , \WGRY[1] , \WGRY[2] , \WGRY[3] , 
        \WGRY[4] , \WGRY[5] , \WGRY[6] , \RGRYSYNC[0] , \RGRYSYNC[1] , 
        \RGRYSYNC[2] , \RGRYSYNC[3] , \RGRYSYNC[4] , \RGRYSYNC[5] , 
        \RGRYSYNC[6] , EMPTYINT, MEMORYRE, MEMRENEG, DVLDI, \RGRY[0] , 
        \RGRY[1] , \RGRY[2] , \RGRY[3] , \RGRY[4] , \RGRY[5] , 
        \RGRY[6] , \WGRYSYNC[0] , \WGRYSYNC[1] , \WGRYSYNC[2] , 
        \WGRYSYNC[3] , \WGRYSYNC[4] , \WGRYSYNC[5] , \WGRYSYNC[6] , 
        \QXI[0] , \QXI[1] , \QXI[2] , \QXI[3] , \QXI[4] , \QXI[5] , 
        \QXI[6] , \QXI[7] , DFN1C0_7_Q, DFN1C0_5_Q, DFN1C0_6_Q, 
        DFN1C0_14_Q, DFN1C0_3_Q, DFN1C0_13_Q, DFN1C0_11_Q, XNOR3_3_Y, 
        XOR3_3_Y, XNOR3_0_Y, XOR3_1_Y, XNOR3_1_Y, XNOR3_6_Y, XOR2_6_Y, 
        XOR2_11_Y, XOR2_23_Y, XOR2_24_Y, XOR2_36_Y, XOR2_39_Y, 
        XOR2_31_Y, AND2_17_Y, AND2_8_Y, AND2_21_Y, AND2_1_Y, AND2_7_Y, 
        AND2_0_Y, XOR2_32_Y, XOR2_2_Y, XOR2_3_Y, XOR2_1_Y, XOR2_4_Y, 
        XOR2_12_Y, XOR2_29_Y, AND2_31_Y, AO1_11_Y, AND2_28_Y, AO1_4_Y, 
        AND2_19_Y, AND2_13_Y, AND2_3_Y, AND2_12_Y, AND2_11_Y, AO1_13_Y, 
        AND2_24_Y, AND2_29_Y, AO1_5_Y, AO1_6_Y, AO1_15_Y, AO1_3_Y, 
        AO1_12_Y, XOR2_7_Y, XOR2_27_Y, XOR2_40_Y, XOR2_20_Y, XOR2_18_Y, 
        XOR2_28_Y, NAND2_1_Y, XOR2_17_Y, XOR2_14_Y, XOR2_9_Y, 
        XOR2_30_Y, XOR2_25_Y, XOR2_15_Y, XOR2_21_Y, AND2_20_Y, 
        AND2_4_Y, AND2_2_Y, AND2_22_Y, AND2_5_Y, AND2_23_Y, XOR2_19_Y, 
        XOR2_16_Y, XOR2_8_Y, XOR2_37_Y, XOR2_35_Y, XOR2_33_Y, XOR2_0_Y, 
        AND2_16_Y, AO1_8_Y, AND2_9_Y, AO1_1_Y, AND2_30_Y, AND2_27_Y, 
        AND2_10_Y, AND2_6_Y, AND2_26_Y, AO1_9_Y, AND2_25_Y, AND2_14_Y, 
        AO1_0_Y, AO1_14_Y, AO1_2_Y, AO1_10_Y, AO1_7_Y, XOR2_10_Y, 
        XOR2_34_Y, XOR2_13_Y, XOR2_26_Y, XOR2_5_Y, XOR2_38_Y, 
        XNOR3_7_Y, XOR3_2_Y, XNOR3_4_Y, XOR3_0_Y, XNOR3_5_Y, XNOR3_2_Y, 
        DFN1C0_15_Q, DFN1C0_0_Q, DFN1C0_4_Q, DFN1C0_10_Q, DFN1C0_2_Q, 
        DFN1C0_8_Q, DFN1C0_12_Q, \RAM4K9_QXI[7]_DOUTA0 , 
        \RAM4K9_QXI[7]_DOUTA1 , \RAM4K9_QXI[7]_DOUTA2 , 
        \RAM4K9_QXI[7]_DOUTA3 , \RAM4K9_QXI[7]_DOUTA4 , 
        \RAM4K9_QXI[7]_DOUTA5 , \RAM4K9_QXI[7]_DOUTA6 , 
        \RAM4K9_QXI[7]_DOUTA7 , AND3_3_Y, XNOR2_11_Y, XNOR2_5_Y, 
        XNOR2_3_Y, XNOR2_6_Y, XNOR2_7_Y, XNOR2_12_Y, XNOR2_4_Y, 
        AND3_2_Y, AND2_18_Y, DFN1C0_9_Q, AND2A_0_Y, DFN1C0_1_Q, 
        AND3_0_Y, XOR2_22_Y, XNOR2_1_Y, XNOR2_8_Y, XNOR2_10_Y, 
        XNOR2_9_Y, XNOR2_0_Y, XNOR2_2_Y, AND3_1_Y, AND2_15_Y, 
        NAND2_0_Y, VCC, GND;
    wire GND_power_net1;
    wire VCC_power_net1;
    assign GND = GND_power_net1;
    assign VCC = VCC_power_net1;
    
    XNOR3 XNOR3_5 (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), .C(
        \WGRYSYNC[4] ), .Y(XNOR3_5_Y));
    DFN1C0 \DFN1C0_RGRYSYNC[4]  (.D(DFN1C0_2_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[4] ));
    AND2 AND2_2 (.A(\MEM_WADDR[3] ), .B(GND), .Y(AND2_2_Y));
    AND2 AND2_20 (.A(\MEM_WADDR[1] ), .B(GND), .Y(AND2_20_Y));
    AO1 AO1_11 (.A(XOR2_1_Y), .B(AND2_8_Y), .C(AND2_21_Y), .Y(AO1_11_Y)
        );
    AND2 AND2_11 (.A(AND2_13_Y), .B(XOR2_4_Y), .Y(AND2_11_Y));
    AND2 AND2_22 (.A(\MEM_WADDR[4] ), .B(GND), .Y(AND2_22_Y));
    XOR2 \XOR2_WBINNXTSHIFT[2]  (.A(XOR2_34_Y), .B(AO1_0_Y), .Y(
        \WBINNXTSHIFT[2] ));
    XNOR2 XNOR2_9 (.A(\RBINSYNCSHIFT[3] ), .B(\WBINNXTSHIFT[3] ), .Y(
        XNOR2_9_Y));
    DFN1C0 DFN1C0_FULL (.D(FULLINT), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(FULL));
    XOR2 XOR2_19 (.A(\MEM_WADDR[0] ), .B(MEMORYWE), .Y(XOR2_19_Y));
    XOR2 XOR2_1 (.A(\MEM_RADDR[3] ), .B(GND), .Y(XOR2_1_Y));
    XOR2 XOR2_23 (.A(\RBINNXTSHIFT[2] ), .B(\RBINNXTSHIFT[3] ), .Y(
        XOR2_23_Y));
    DFN1E1C0 \DFN1E1C0_Q[1]  (.D(\QXI[1] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[1]));
    DFN1C0 \DFN1C0_RGRYSYNC[3]  (.D(DFN1C0_10_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[3] ));
    DFN1E1C0 \DFN1E1C0_Q[4]  (.D(\QXI[4] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[4]));
    DFN1E1C0 \DFN1E1C0_Q[7]  (.D(\QXI[7] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[7]));
    XOR2 XOR2_38 (.A(\MEM_WADDR[6] ), .B(GND), .Y(XOR2_38_Y));
    BUFF BUFF_READDOMAIN_WMSB (.A(\WGRYSYNC[6] ), .Y(READDOMAIN_WMSB));
    XOR2 \XOR2_RBINNXTSHIFT[0]  (.A(\MEM_RADDR[0] ), .B(MEMORYRE), .Y(
        \RBINNXTSHIFT[0] ));
    AO1 AO1_7 (.A(AND2_30_Y), .B(AO1_2_Y), .C(AO1_1_Y), .Y(AO1_7_Y));
    DFN1C0 DFN1C0_9 (.D(VCC), .CLK(WCLOCK), .CLR(RESET), .Q(DFN1C0_9_Q)
        );
    DFN1C0 \DFN1C0_WGRY[6]  (.D(XOR2_21_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[6] ));
    AND2 AND2_18 (.A(XNOR2_12_Y), .B(XNOR2_4_Y), .Y(AND2_18_Y));
    AND2 AND2_15 (.A(XNOR2_0_Y), .B(XNOR2_2_Y), .Y(AND2_15_Y));
    DFN1C0 DFN1C0_WRITE_RESET_P (.D(DFN1C0_9_Q), .CLK(WCLOCK), .CLR(
        RESET), .Q(WRITE_RESET_P));
    DFN1C0 DFN1C0_11 (.D(\WGRY[6] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_11_Q));
    DFN1C0 DFN1C0_0 (.D(\RGRY[1] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_0_Q));
    AND2 AND2_1 (.A(\MEM_RADDR[4] ), .B(GND), .Y(AND2_1_Y));
    DFN1C0 \DFN1C0_MEM_WADDR[0]  (.D(\WBINNXTSHIFT[0] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[0] ));
    DFN1C0 \DFN1C0_MEM_WADDR[3]  (.D(\WBINNXTSHIFT[3] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[3] ));
    DFN1C0 \DFN1C0_MEM_RADDR[1]  (.D(\RBINNXTSHIFT[1] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[1] ));
    AO1 AO1_8 (.A(XOR2_37_Y), .B(AND2_4_Y), .C(AND2_2_Y), .Y(AO1_8_Y));
    AND2 AND2_10 (.A(AND2_27_Y), .B(AND2_30_Y), .Y(AND2_10_Y));
    AND2 AND2_7 (.A(\MEM_RADDR[5] ), .B(GND), .Y(AND2_7_Y));
    DFN1C0 \DFN1C0_RGRYSYNC[6]  (.D(DFN1C0_12_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[6] ));
    XOR2 XOR2_20 (.A(\MEM_RADDR[4] ), .B(GND), .Y(XOR2_20_Y));
    AND2 AND2_12 (.A(AND2_31_Y), .B(XOR2_3_Y), .Y(AND2_12_Y));
    DFN1C0 \DFN1C0_WGRY[5]  (.D(XOR2_15_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[5] ));
    AO1 AO1_15 (.A(AND2_28_Y), .B(AO1_5_Y), .C(AO1_11_Y), .Y(AO1_15_Y));
    DFN1C0 \DFN1C0_MEM_WADDR[4]  (.D(\WBINNXTSHIFT[4] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[4] ));
    XOR2 \XOR2_WBINNXTSHIFT[0]  (.A(\MEM_WADDR[0] ), .B(MEMORYWE), .Y(
        \WBINNXTSHIFT[0] ));
    XNOR3 \XNOR3_WBINSYNCSHIFT[2]  (.A(\WGRYSYNC[3] ), .B(
        \WGRYSYNC[2] ), .C(XNOR3_2_Y), .Y(\WBINSYNCSHIFT[2] ));
    DFN1C0 DFN1C0_READ_RESET_P (.D(DFN1C0_1_Q), .CLK(RCLOCK), .CLR(
        RESET), .Q(READ_RESET_P));
    AND2 AND2_EMPTYINT (.A(AND3_3_Y), .B(XNOR2_11_Y), .Y(EMPTYINT));
    XOR2 XOR2_24 (.A(\RBINNXTSHIFT[3] ), .B(\RBINNXTSHIFT[4] ), .Y(
        XOR2_24_Y));
    XOR2 XOR2_21 (.A(\WBINNXTSHIFT[6] ), .B(GND), .Y(XOR2_21_Y));
    XNOR2 \XNOR2_RBINSYNCSHIFT[1]  (.A(XOR3_1_Y), .B(XNOR3_0_Y), .Y(
        \RBINSYNCSHIFT[1] ));
    XOR2 XOR2_16 (.A(\MEM_WADDR[1] ), .B(GND), .Y(XOR2_16_Y));
    DFN1C0 DFN1C0_4 (.D(\RGRY[2] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_4_Q));
    DFN1C0 DFN1C0_14 (.D(\WGRY[3] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_14_Q));
    AND3 AND3_3 (.A(XNOR2_7_Y), .B(AND3_2_Y), .C(AND2_18_Y), .Y(
        AND3_3_Y));
    INV MEMWEBUBBLE (.A(MEMORYWE), .Y(MEMWENEG));
    AND2 AND2_6 (.A(AND2_16_Y), .B(XOR2_8_Y), .Y(AND2_6_Y));
    AND3 AND3_0 (.A(XNOR2_9_Y), .B(AND3_1_Y), .C(AND2_15_Y), .Y(
        AND3_0_Y));
    DFN1C0 \DFN1C0_MEM_RADDR[2]  (.D(\RBINNXTSHIFT[2] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[2] ));
    DFN1C0 \DFN1C0_RGRY[2]  (.D(XOR2_23_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[2] ));
    XOR2 XOR2_33 (.A(\MEM_WADDR[5] ), .B(GND), .Y(XOR2_33_Y));
    XNOR2 XNOR2_2 (.A(\RBINSYNCSHIFT[5] ), .B(\WBINNXTSHIFT[5] ), .Y(
        XNOR2_2_Y));
    AO1 AO1_14 (.A(XOR2_8_Y), .B(AO1_0_Y), .C(AND2_4_Y), .Y(AO1_14_Y));
    XOR2 XOR2_4 (.A(\MEM_RADDR[4] ), .B(GND), .Y(XOR2_4_Y));
    XNOR2 \XNOR2_WBINSYNCSHIFT[3]  (.A(\WGRYSYNC[3] ), .B(XNOR3_5_Y), 
        .Y(\WBINSYNCSHIFT[3] ));
    AND3 AND3_1 (.A(XNOR2_1_Y), .B(XNOR2_8_Y), .C(XNOR2_10_Y), .Y(
        AND3_1_Y));
    AND2 AND2_24 (.A(AND2_3_Y), .B(XOR2_29_Y), .Y(AND2_24_Y));
    XNOR2 XNOR2_0 (.A(\RBINSYNCSHIFT[4] ), .B(\WBINNXTSHIFT[4] ), .Y(
        XNOR2_0_Y));
    AND2 AND2_31 (.A(XOR2_32_Y), .B(XOR2_2_Y), .Y(AND2_31_Y));
    DFN1C0 DFN1C0_15 (.D(\RGRY[0] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_15_Q));
    DFN1C0 DFN1C0_12 (.D(\RGRY[6] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_12_Q));
    XOR2 XOR2_18 (.A(\MEM_RADDR[5] ), .B(GND), .Y(XOR2_18_Y));
    XOR2 \XOR2_RBINNXTSHIFT[4]  (.A(XOR2_20_Y), .B(AO1_15_Y), .Y(
        \RBINNXTSHIFT[4] ));
    DFN1C0 \DFN1C0_RGRY[1]  (.D(XOR2_11_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[1] ));
    DFN1C0 \DFN1C0_RGRYSYNC[5]  (.D(DFN1C0_8_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[5] ));
    DFN1C0 \DFN1C0_WGRY[3]  (.D(XOR2_30_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[3] ));
    XOR2 XOR2_8 (.A(\MEM_WADDR[2] ), .B(GND), .Y(XOR2_8_Y));
    DFN1E1C0 \DFN1E1C0_Q[6]  (.D(\QXI[6] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[6]));
    XOR2 \XOR2_RBINNXTSHIFT[6]  (.A(XOR2_28_Y), .B(AO1_12_Y), .Y(
        \RBINNXTSHIFT[6] ));
    XOR2 XOR2_30 (.A(\WBINNXTSHIFT[3] ), .B(\WBINNXTSHIFT[4] ), .Y(
        XOR2_30_Y));
    INV MEMREBUBBLE (.A(MEMORYRE), .Y(MEMRENEG));
    AND2 AND2_29 (.A(\MEM_RADDR[0] ), .B(MEMORYRE), .Y(AND2_29_Y));
    DFN1C0 \DFN1C0_MEM_RADDR[4]  (.D(\RBINNXTSHIFT[4] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[4] ));
    XNOR3 XNOR3_7 (.A(\WGRYSYNC[3] ), .B(\WGRYSYNC[2] ), .C(
        \WGRYSYNC[1] ), .Y(XNOR3_7_Y));
    XOR2 XOR2_34 (.A(\MEM_WADDR[2] ), .B(GND), .Y(XOR2_34_Y));
    XOR2 XOR2_31 (.A(\RBINNXTSHIFT[6] ), .B(GND), .Y(XOR2_31_Y));
    AND2 AND2_3 (.A(AND2_13_Y), .B(AND2_19_Y), .Y(AND2_3_Y));
    AND2 AND2_30 (.A(XOR2_35_Y), .B(XOR2_33_Y), .Y(AND2_30_Y));
    XOR2 \XOR2_WBINNXTSHIFT[4]  (.A(XOR2_26_Y), .B(AO1_2_Y), .Y(
        \WBINNXTSHIFT[4] ));
    XNOR2 XNOR2_6 (.A(\RBINNXTSHIFT[2] ), .B(\WBINSYNCSHIFT[2] ), .Y(
        XNOR2_6_Y));
    AND2 AND2_14 (.A(\MEM_WADDR[0] ), .B(MEMORYWE), .Y(AND2_14_Y));
    DFN1C0 \DFN1C0_MEM_RADDR[5]  (.D(\RBINNXTSHIFT[5] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[5] ));
    XOR2 \XOR2_WBINNXTSHIFT[6]  (.A(XOR2_38_Y), .B(AO1_7_Y), .Y(
        \WBINNXTSHIFT[6] ));
    XNOR2 XNOR2_11 (.A(\RBINNXTSHIFT[6] ), .B(READDOMAIN_WMSB), .Y(
        XNOR2_11_Y));
    AO1 AO1_2 (.A(AND2_9_Y), .B(AO1_0_Y), .C(AO1_8_Y), .Y(AO1_2_Y));
    DFN1C0 \DFN1C0_WGRY[0]  (.D(XOR2_17_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[0] ));
    AND2 AND2_26 (.A(AND2_27_Y), .B(XOR2_35_Y), .Y(AND2_26_Y));
    XOR3 \XOR3_RBINSYNCSHIFT[4]  (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), 
        .C(\RGRYSYNC[4] ), .Y(\RBINSYNCSHIFT[4] ));
    XOR2 XOR2_9 (.A(\WBINNXTSHIFT[2] ), .B(\WBINNXTSHIFT[3] ), .Y(
        XOR2_9_Y));
    RAM4K9 \RAM4K9_QXI[7]  (.ADDRA11(GND), .ADDRA10(GND), .ADDRA9(GND), 
        .ADDRA8(GND), .ADDRA7(GND), .ADDRA6(GND), .ADDRA5(
        \MEM_WADDR[5] ), .ADDRA4(\MEM_WADDR[4] ), .ADDRA3(
        \MEM_WADDR[3] ), .ADDRA2(\MEM_WADDR[2] ), .ADDRA1(
        \MEM_WADDR[1] ), .ADDRA0(\MEM_WADDR[0] ), .ADDRB11(GND), 
        .ADDRB10(GND), .ADDRB9(GND), .ADDRB8(GND), .ADDRB7(GND), 
        .ADDRB6(GND), .ADDRB5(\MEM_RADDR[5] ), .ADDRB4(\MEM_RADDR[4] ), 
        .ADDRB3(\MEM_RADDR[3] ), .ADDRB2(\MEM_RADDR[2] ), .ADDRB1(
        \MEM_RADDR[1] ), .ADDRB0(\MEM_RADDR[0] ), .DINA8(GND), .DINA7(
        DATA[7]), .DINA6(DATA[6]), .DINA5(DATA[5]), .DINA4(DATA[4]), 
        .DINA3(DATA[3]), .DINA2(DATA[2]), .DINA1(DATA[1]), .DINA0(
        DATA[0]), .DINB8(GND), .DINB7(GND), .DINB6(GND), .DINB5(GND), 
        .DINB4(GND), .DINB3(GND), .DINB2(GND), .DINB1(GND), .DINB0(GND)
        , .WIDTHA0(VCC), .WIDTHA1(VCC), .WIDTHB0(VCC), .WIDTHB1(VCC), 
        .PIPEA(GND), .PIPEB(GND), .WMODEA(GND), .WMODEB(GND), .BLKA(
        MEMWENEG), .BLKB(MEMRENEG), .WENA(GND), .WENB(VCC), .CLKA(
        WCLOCK), .CLKB(RCLOCK), .RESET(WRITE_RESET_P), .DOUTA8(), 
        .DOUTA7(\RAM4K9_QXI[7]_DOUTA7 ), .DOUTA6(
        \RAM4K9_QXI[7]_DOUTA6 ), .DOUTA5(\RAM4K9_QXI[7]_DOUTA5 ), 
        .DOUTA4(\RAM4K9_QXI[7]_DOUTA4 ), .DOUTA3(
        \RAM4K9_QXI[7]_DOUTA3 ), .DOUTA2(\RAM4K9_QXI[7]_DOUTA2 ), 
        .DOUTA1(\RAM4K9_QXI[7]_DOUTA1 ), .DOUTA0(
        \RAM4K9_QXI[7]_DOUTA0 ), .DOUTB8(), .DOUTB7(\QXI[7] ), .DOUTB6(
        \QXI[6] ), .DOUTB5(\QXI[5] ), .DOUTB4(\QXI[4] ), .DOUTB3(
        \QXI[3] ), .DOUTB2(\QXI[2] ), .DOUTB1(\QXI[1] ), .DOUTB0(
        \QXI[0] ));
    AND2 AND2_23 (.A(\MEM_WADDR[6] ), .B(GND), .Y(AND2_23_Y));
    DFN1C0 DFN1C0_DVLD (.D(DVLDI), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DVLD));
    XNOR2 XNOR2_4 (.A(\RBINNXTSHIFT[5] ), .B(\WBINSYNCSHIFT[5] ), .Y(
        XNOR2_4_Y));
    DFN1C0 \DFN1C0_WGRYSYNC[1]  (.D(DFN1C0_5_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[1] ));
    XOR2 XOR2_5 (.A(\MEM_WADDR[5] ), .B(GND), .Y(XOR2_5_Y));
    AND2 AND2_19 (.A(XOR2_4_Y), .B(XOR2_12_Y), .Y(AND2_19_Y));
    DFN1C0 DFN1C0_6 (.D(\WGRY[2] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_6_Q));
    DFN1E1C0 \DFN1E1C0_Q[0]  (.D(\QXI[0] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[0]));
    DFN1C0 \DFN1C0_MEM_RADDR[6]  (.D(\RBINNXTSHIFT[6] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[6] ));
    XOR2 XOR2_22 (.A(\RBINSYNCSHIFT[6] ), .B(\WBINNXTSHIFT[6] ), .Y(
        XOR2_22_Y));
    AO1 AO1_1 (.A(XOR2_33_Y), .B(AND2_22_Y), .C(AND2_5_Y), .Y(AO1_1_Y));
    DFN1C0 DFN1C0_10 (.D(\RGRY[3] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_10_Q));
    XOR2 XOR2_13 (.A(\MEM_WADDR[3] ), .B(GND), .Y(XOR2_13_Y));
    DFN1C0 \DFN1C0_WGRYSYNC[2]  (.D(DFN1C0_6_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[2] ));
    DFN1C0 \DFN1C0_WGRYSYNC[0]  (.D(DFN1C0_7_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[0] ));
    AO1 AO1_3 (.A(XOR2_4_Y), .B(AO1_15_Y), .C(AND2_1_Y), .Y(AO1_3_Y));
    XOR2 \XOR2_RBINNXTSHIFT[3]  (.A(XOR2_40_Y), .B(AO1_6_Y), .Y(
        \RBINNXTSHIFT[3] ));
    DFN1C0 DFN1C0_3 (.D(\WGRY[4] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_3_Q));
    AND2 AND2_16 (.A(XOR2_19_Y), .B(XOR2_16_Y), .Y(AND2_16_Y));
    AND2 AND2_13 (.A(AND2_31_Y), .B(AND2_28_Y), .Y(AND2_13_Y));
    XOR2 XOR2_10 (.A(\MEM_WADDR[1] ), .B(GND), .Y(XOR2_10_Y));
    XNOR2 XNOR2_1 (.A(\RBINSYNCSHIFT[0] ), .B(\WBINNXTSHIFT[0] ), .Y(
        XNOR2_1_Y));
    XNOR3 XNOR3_6 (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), .C(
        \RGRYSYNC[4] ), .Y(XNOR3_6_Y));
    XOR3 \XOR3_WBINSYNCSHIFT[4]  (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), 
        .C(\WGRYSYNC[4] ), .Y(\WBINSYNCSHIFT[4] ));
    DFN1C0 \DFN1C0_RGRY[4]  (.D(XOR2_36_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[4] ));
    DFN1C0 DFN1C0_2 (.D(\RGRY[4] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_2_Q));
    DFN1C0 \DFN1C0_MEM_WADDR[2]  (.D(\WBINNXTSHIFT[2] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[2] ));
    XOR2 XOR2_27 (.A(\MEM_RADDR[2] ), .B(GND), .Y(XOR2_27_Y));
    XOR3 XOR3_3 (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), .C(
        \RGRYSYNC[4] ), .Y(XOR3_3_Y));
    AND2 AND2_MEMORYRE (.A(NAND2_1_Y), .B(RE), .Y(MEMORYRE));
    XOR2 \XOR2_WBINNXTSHIFT[3]  (.A(XOR2_13_Y), .B(AO1_14_Y), .Y(
        \WBINNXTSHIFT[3] ));
    XOR2 XOR2_7 (.A(\MEM_RADDR[1] ), .B(GND), .Y(XOR2_7_Y));
    AND2 AND2_5 (.A(\MEM_WADDR[5] ), .B(GND), .Y(AND2_5_Y));
    XOR2 XOR2_14 (.A(\WBINNXTSHIFT[1] ), .B(\WBINNXTSHIFT[2] ), .Y(
        XOR2_14_Y));
    XNOR3 XNOR3_1 (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), .C(
        \RGRYSYNC[4] ), .Y(XNOR3_1_Y));
    XNOR2 XNOR2_3 (.A(\RBINNXTSHIFT[1] ), .B(\WBINSYNCSHIFT[1] ), .Y(
        XNOR2_3_Y));
    DFN1C0 DFN1C0_7 (.D(\WGRY[0] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_7_Q));
    XOR2 XOR2_11 (.A(\RBINNXTSHIFT[1] ), .B(\RBINNXTSHIFT[2] ), .Y(
        XOR2_11_Y));
    XOR2 XOR2_25 (.A(\WBINNXTSHIFT[4] ), .B(\WBINNXTSHIFT[5] ), .Y(
        XOR2_25_Y));
    XNOR3 XNOR3_3 (.A(\RGRYSYNC[3] ), .B(\RGRYSYNC[2] ), .C(
        \RGRYSYNC[1] ), .Y(XNOR3_3_Y));
    AO1 AO1_6 (.A(XOR2_3_Y), .B(AO1_5_Y), .C(AND2_8_Y), .Y(AO1_6_Y));
    DFN1C0 \DFN1C0_MEM_RADDR[3]  (.D(\RBINNXTSHIFT[3] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[3] ));
    AND3 AND3_2 (.A(XNOR2_5_Y), .B(XNOR2_3_Y), .C(XNOR2_6_Y), .Y(
        AND3_2_Y));
    AO1 AO1_12 (.A(AND2_19_Y), .B(AO1_15_Y), .C(AO1_4_Y), .Y(AO1_12_Y));
    XOR2 XOR2_32 (.A(\MEM_RADDR[0] ), .B(MEMORYRE), .Y(XOR2_32_Y));
    AND2 AND2_9 (.A(XOR2_8_Y), .B(XOR2_37_Y), .Y(AND2_9_Y));
    DFN1E1C0 \DFN1E1C0_Q[5]  (.D(\QXI[5] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[5]));
    XNOR2 \XNOR2_RBINSYNCSHIFT[3]  (.A(\RGRYSYNC[3] ), .B(XNOR3_1_Y), 
        .Y(\RBINSYNCSHIFT[3] ));
    AO1 AO1_9 (.A(XOR2_0_Y), .B(AO1_7_Y), .C(AND2_23_Y), .Y(AO1_9_Y));
    NAND2 NAND2_0 (.A(FULL), .B(VCC), .Y(NAND2_0_Y));
    XNOR3 XNOR3_0 (.A(\RGRYSYNC[3] ), .B(\RGRYSYNC[2] ), .C(
        \RGRYSYNC[1] ), .Y(XNOR3_0_Y));
    DFN1C0 \DFN1C0_RGRY[6]  (.D(XOR2_31_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[6] ));
    AND2 AND2_27 (.A(AND2_16_Y), .B(AND2_9_Y), .Y(AND2_27_Y));
    DFN1C0 DFN1C0_DVLDI (.D(AND2A_0_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(DVLDI));
    XNOR2 XNOR2_10 (.A(\RBINSYNCSHIFT[2] ), .B(\WBINNXTSHIFT[2] ), .Y(
        XNOR2_10_Y));
    BUFF \BUFF_RBINSYNCSHIFT[6]  (.A(\RGRYSYNC[6] ), .Y(
        \RBINSYNCSHIFT[6] ));
    AND2 AND2_MEMORYWE (.A(NAND2_0_Y), .B(WE), .Y(MEMORYWE));
    DFN1C0 \DFN1C0_WGRY[2]  (.D(XOR2_9_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[2] ));
    AO1 AO1_0 (.A(XOR2_16_Y), .B(AND2_14_Y), .C(AND2_20_Y), .Y(AO1_0_Y)
        );
    XOR2 XOR2_29 (.A(\MEM_RADDR[6] ), .B(GND), .Y(XOR2_29_Y));
    XOR2 XOR2_40 (.A(\MEM_RADDR[3] ), .B(GND), .Y(XOR2_40_Y));
    DFN1C0 \DFN1C0_RGRYSYNC[1]  (.D(DFN1C0_0_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[1] ));
    XOR3 XOR3_0 (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), .C(
        \WGRYSYNC[4] ), .Y(XOR3_0_Y));
    XOR2 XOR2_2 (.A(\MEM_RADDR[1] ), .B(GND), .Y(XOR2_2_Y));
    DFN1C0 DFN1C0_8 (.D(\RGRY[5] ), .CLK(WCLOCK), .CLR(WRITE_RESET_P), 
        .Q(DFN1C0_8_Q));
    DFN1C0 \DFN1C0_RGRY[5]  (.D(XOR2_39_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[5] ));
    XOR2 XOR2_37 (.A(\MEM_WADDR[3] ), .B(GND), .Y(XOR2_37_Y));
    AND2A AND2A_0 (.A(EMPTY), .B(RE), .Y(AND2A_0_Y));
    XNOR3 \XNOR3_WBINSYNCSHIFT[0]  (.A(\WGRYSYNC[0] ), .B(XOR3_2_Y), 
        .C(XNOR3_7_Y), .Y(\WBINSYNCSHIFT[0] ));
    XOR2 \XOR2_RBINNXTSHIFT[5]  (.A(XOR2_18_Y), .B(AO1_3_Y), .Y(
        \RBINNXTSHIFT[5] ));
    DFN1C0 \DFN1C0_RGRYSYNC[2]  (.D(DFN1C0_4_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[2] ));
    AO1 AO1_10 (.A(XOR2_35_Y), .B(AO1_2_Y), .C(AND2_22_Y), .Y(AO1_10_Y)
        );
    XOR2 XOR2_35 (.A(\MEM_WADDR[4] ), .B(GND), .Y(XOR2_35_Y));
    DFN1C0 \DFN1C0_RGRYSYNC[0]  (.D(DFN1C0_15_Q), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\RGRYSYNC[0] ));
    DFN1C0 \DFN1C0_WGRY[1]  (.D(XOR2_14_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[1] ));
    DFN1P0 DFN1P0_EMPTY (.D(EMPTYINT), .CLK(RCLOCK), .PRE(READ_RESET_P)
        , .Q(EMPTY));
    DFN1E1C0 \DFN1E1C0_Q[3]  (.D(\QXI[3] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[3]));
    DFN1C0 \DFN1C0_WGRYSYNC[4]  (.D(DFN1C0_3_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[4] ));
    AND2 AND2_0 (.A(\MEM_RADDR[6] ), .B(GND), .Y(AND2_0_Y));
    AND2 AND2_17 (.A(\MEM_RADDR[1] ), .B(GND), .Y(AND2_17_Y));
    XNOR2 \XNOR2_WBINSYNCSHIFT[1]  (.A(XOR3_0_Y), .B(XNOR3_4_Y), .Y(
        \WBINSYNCSHIFT[1] ));
    XOR2 XOR2_6 (.A(\RBINNXTSHIFT[0] ), .B(\RBINNXTSHIFT[1] ), .Y(
        XOR2_6_Y));
    AO1 AO1_13 (.A(XOR2_29_Y), .B(AO1_12_Y), .C(AND2_0_Y), .Y(AO1_13_Y)
        );
    XNOR3 \XNOR3_RBINSYNCSHIFT[2]  (.A(\RGRYSYNC[3] ), .B(
        \RGRYSYNC[2] ), .C(XNOR3_6_Y), .Y(\RBINSYNCSHIFT[2] ));
    DFN1C0 \DFN1C0_MEM_WADDR[6]  (.D(\WBINNXTSHIFT[6] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[6] ));
    XOR2 \XOR2_WBINNXTSHIFT[5]  (.A(XOR2_5_Y), .B(AO1_10_Y), .Y(
        \WBINNXTSHIFT[5] ));
    DFN1C0 \DFN1C0_WGRYSYNC[3]  (.D(DFN1C0_14_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[3] ));
    XNOR2 XNOR2_12 (.A(\RBINNXTSHIFT[4] ), .B(\WBINSYNCSHIFT[4] ), .Y(
        XNOR2_12_Y));
    XNOR2 XNOR2_7 (.A(\RBINNXTSHIFT[3] ), .B(\WBINSYNCSHIFT[3] ), .Y(
        XNOR2_7_Y));
    XOR2 XOR2_12 (.A(\MEM_RADDR[5] ), .B(GND), .Y(XOR2_12_Y));
    DFN1C0 DFN1C0_5 (.D(\WGRY[1] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_5_Q));
    XOR2 XOR2_26 (.A(\MEM_WADDR[4] ), .B(GND), .Y(XOR2_26_Y));
    DFN1C0 DFN1C0_1 (.D(VCC), .CLK(RCLOCK), .CLR(RESET), .Q(DFN1C0_1_Q)
        );
    AND2 AND2_4 (.A(\MEM_WADDR[2] ), .B(GND), .Y(AND2_4_Y));
    AND2 AND2_FULLINT (.A(AND3_0_Y), .B(XOR2_22_Y), .Y(FULLINT));
    DFN1C0 \DFN1C0_WGRYSYNC[6]  (.D(DFN1C0_11_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[6] ));
    DFN1E1C0 \DFN1E1C0_Q[2]  (.D(\QXI[2] ), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .E(DVLDI), .Q(Q[2]));
    XNOR2 XNOR2_5 (.A(\RBINNXTSHIFT[0] ), .B(\WBINSYNCSHIFT[0] ), .Y(
        XNOR2_5_Y));
    AO1 AO1_5 (.A(XOR2_2_Y), .B(AND2_29_Y), .C(AND2_17_Y), .Y(AO1_5_Y));
    DFN1C0 \DFN1C0_RGRY[3]  (.D(XOR2_24_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[3] ));
    XOR3 XOR3_2 (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), .C(
        \WGRYSYNC[4] ), .Y(XOR3_2_Y));
    XOR2 XOR2_39 (.A(\RBINNXTSHIFT[5] ), .B(\RBINNXTSHIFT[6] ), .Y(
        XOR2_39_Y));
    AND2 AND2_8 (.A(\MEM_RADDR[2] ), .B(GND), .Y(AND2_8_Y));
    XOR2 XOR2_3 (.A(\MEM_RADDR[2] ), .B(GND), .Y(XOR2_3_Y));
    XOR3 XOR3_1 (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), .C(
        \RGRYSYNC[4] ), .Y(XOR3_1_Y));
    XNOR3 \XNOR3_RBINSYNCSHIFT[0]  (.A(\RGRYSYNC[0] ), .B(XOR3_3_Y), 
        .C(XNOR3_3_Y), .Y(\RBINSYNCSHIFT[0] ));
    DFN1C0 \DFN1C0_MEM_WADDR[1]  (.D(\WBINNXTSHIFT[1] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[1] ));
    XOR2 \XOR2_RBINNXTSHIFT[1]  (.A(XOR2_7_Y), .B(AND2_29_Y), .Y(
        \RBINNXTSHIFT[1] ));
    XOR2 XOR2_17 (.A(\WBINNXTSHIFT[0] ), .B(\WBINNXTSHIFT[1] ), .Y(
        XOR2_17_Y));
    DFN1C0 DFN1C0_13 (.D(\WGRY[5] ), .CLK(RCLOCK), .CLR(READ_RESET_P), 
        .Q(DFN1C0_13_Q));
    XOR2 XOR2_28 (.A(\MEM_RADDR[6] ), .B(GND), .Y(XOR2_28_Y));
    XOR2 XOR2_15 (.A(\WBINNXTSHIFT[5] ), .B(\WBINNXTSHIFT[6] ), .Y(
        XOR2_15_Y));
    DFN1C0 \DFN1C0_MEM_WADDR[5]  (.D(\WBINNXTSHIFT[5] ), .CLK(WCLOCK), 
        .CLR(WRITE_RESET_P), .Q(\MEM_WADDR[5] ));
    DFN1C0 \DFN1C0_MEM_RADDR[0]  (.D(\RBINNXTSHIFT[0] ), .CLK(RCLOCK), 
        .CLR(READ_RESET_P), .Q(\MEM_RADDR[0] ));
    DFN1C0 \DFN1C0_RGRY[0]  (.D(XOR2_6_Y), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\RGRY[0] ));
    AND2 AND2_21 (.A(\MEM_RADDR[3] ), .B(GND), .Y(AND2_21_Y));
    XOR2 \XOR2_WBINNXTSHIFT[1]  (.A(XOR2_10_Y), .B(AND2_14_Y), .Y(
        \WBINNXTSHIFT[1] ));
    DFN1C0 \DFN1C0_WGRY[4]  (.D(XOR2_25_Y), .CLK(WCLOCK), .CLR(
        WRITE_RESET_P), .Q(\WGRY[4] ));
    XOR2 \XOR2_WBINSYNCSHIFT[5]  (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), 
        .Y(\WBINSYNCSHIFT[5] ));
    XOR2 XOR2_0 (.A(\MEM_WADDR[6] ), .B(GND), .Y(XOR2_0_Y));
    NAND2 NAND2_1 (.A(EMPTY), .B(VCC), .Y(NAND2_1_Y));
    AO1 AO1_4 (.A(XOR2_12_Y), .B(AND2_1_Y), .C(AND2_7_Y), .Y(AO1_4_Y));
    XOR2 \XOR2_RBINSYNCSHIFT[5]  (.A(\RGRYSYNC[6] ), .B(\RGRYSYNC[5] ), 
        .Y(\RBINSYNCSHIFT[5] ));
    XNOR3 XNOR3_4 (.A(\WGRYSYNC[3] ), .B(\WGRYSYNC[2] ), .C(
        \WGRYSYNC[1] ), .Y(XNOR3_4_Y));
    XOR2 \XOR2_RBINNXTSHIFT[2]  (.A(XOR2_27_Y), .B(AO1_5_Y), .Y(
        \RBINNXTSHIFT[2] ));
    XOR2 XOR2_36 (.A(\RBINNXTSHIFT[4] ), .B(\RBINNXTSHIFT[5] ), .Y(
        XOR2_36_Y));
    XNOR2 XNOR2_8 (.A(\RBINSYNCSHIFT[1] ), .B(\WBINNXTSHIFT[1] ), .Y(
        XNOR2_8_Y));
    XNOR3 XNOR3_2 (.A(\WGRYSYNC[6] ), .B(\WGRYSYNC[5] ), .C(
        \WGRYSYNC[4] ), .Y(XNOR3_2_Y));
    AND2 AND2_28 (.A(XOR2_3_Y), .B(XOR2_1_Y), .Y(AND2_28_Y));
    AND2 AND2_25 (.A(AND2_10_Y), .B(XOR2_0_Y), .Y(AND2_25_Y));
    DFN1C0 \DFN1C0_WGRYSYNC[5]  (.D(DFN1C0_13_Q), .CLK(RCLOCK), .CLR(
        READ_RESET_P), .Q(\WGRYSYNC[5] ));
    GND GND_power_inst1 (.Y(GND_power_net1));
    VCC VCC_power_inst1 (.Y(VCC_power_net1));
    
endmodule

// _Disclaimer: Please leave the following comments in the file, they are for internal purposes only._


// _GEN_File_Contents_

// Version:11.0.0.23
// ACTGENU_CALL:1
// BATCH:T
// FAM:PA3SOC2
// OUTFORMAT:Verilog
// LPMTYPE:LPM_SOFTFIFO
// LPM_HINT:MEMFF
// INSERT_PAD:NO
// INSERT_IOREG:NO
// GEN_BHV_VHDL_VAL:F
// GEN_BHV_VERILOG_VAL:F
// MGNTIMER:F
// MGNCMPL:T
// DESDIR:C:/Users/mttschlt/UMKarts/gc/smartgen\IR_QUEUE
// GEN_BEHV_MODULE:F
// SMARTGEN_DIE:IP4X3M1
// SMARTGEN_PACKAGE:fg484
// AGENIII_IS_SUBPROJECT_LIBERO:T
// WWIDTH:8
// WDEPTH:64
// RWIDTH:8
// RDEPTH:64
// CLKS:2
// WCLOCK_PN:WCLOCK
// RCLOCK_PN:RCLOCK
// WCLK_EDGE:RISE
// RCLK_EDGE:RISE
// ACLR_PN:RESET
// RESET_POLARITY:0
// INIT_RAM:F
// WE_POLARITY:1
// RE_POLARITY:1
// FF_PN:FULL
// AF_PN:AFULL
// WACK_PN:WACK
// OVRFLOW_PN:OVERFLOW
// WRCNT_PN:WRCNT
// WE_PN:WE
// EF_PN:EMPTY
// AE_PN:AEMPTY
// DVLD_PN:DVLD
// UDRFLOW_PN:UNDERFLOW
// RDCNT_PN:RDCNT
// RE_PN:RE
// CONTROLLERONLY:F
// FSTOP:YES
// ESTOP:YES
// WRITEACK:NO
// OVERFLOW:NO
// WRCOUNT:NO
// DATAVALID:YES
// UNDERFLOW:NO
// RDCOUNT:NO
// AF_PORT_PN:AFVAL
// AE_PORT_PN:AEVAL
// AFFLAG:NONE
// AEFLAG:NONE
// DATA_IN_PN:DATA
// DATA_OUT_PN:Q
// CASCADE:1

// _End_Comments_

